### ISSUE TITLE
rts: unify LLVM codegen node layout with Zig RTS node layout

### ISSUE THREAD

**Issue by adinapoli** [adinapoli/rusholme#422]
## Context
PR #385 (issue #385) introduced a proper variable-length node layout for the Zig RTS:

```
{ tag: u64, n_fields: u32, _pad: u32, field[0]…field[N-1]: u64 }
```

The LLVM codegen (`src/backend/grin_to_llvm.zig`) currently allocates nodes via `malloc` using its own layout:

```llvm
{ i64 tag, ptr field0, … }
```

and does not yet call `rts_alloc`/`rts_store_field`.

## Shortcoming
The two node layouts are incompatible:
- The Zig RTS uses `n_fields: u32` in the header; the LLVM layout has no such field.
- The Zig RTS stores all fields as `u64` (pointer-or-scalar); the LLVM layout uses `ptr` (opaque pointer).
- LLVM-generated code never calls `rts_alloc`, so the heap arena is not used for LLVM-emitted allocations.

Until these are unified, any RTS function that receives a node allocated by LLVM-generated code (e.g., `rts_eval`, `rts_store_field`) will read garbage from the header.

## Deliverable
1. Update `grin_to_llvm.zig` to emit calls to `rts_alloc(tag, n_fields)` instead of `malloc`.
2. Emit `rts_store_field(node, index, value)` calls instead of direct GEP stores.
3. Ensure the LLVM-side struct type declaration matches the Zig-side `Node` layout (16-byte header + trailing u64 array).
4. Add an integration test that exercises the full pipeline: GRIN → LLVM → linked binary that allocates an ADT node and reads it back via an RTS helper.

## References
- `src/rts/node.zig` — Zig-side layout (introduced in #385)
- `src/backend/grin_to_llvm.zig` — LLVM codegen (current malloc-based allocation)
- Issue #55 — LLVM codegen for GRIN expressions (parent epic)
